<script setup lang="ts">
import {
  ArrowRight,
  ArrowUpRight,
  Search,
  ChevronDown,
  ChevronRight,
  Check,
  Copy,
  Menu,
  X,
  Sun,
  Moon,
  Github,
  Globe,
  BookOpen,
  Code2,
  Terminal,
  Box,
  Blocks,
  Compass,
  FileCode2,
  FolderTree,
  Braces,
  Rocket,
  Workflow,
  LayoutDashboard,
  Database,
  Network,
  GitBranch,
  Clock3,
  Command,
  CircleHelp,
  SlidersHorizontal,
  ExternalLink,
  List,
  CheckCircle2,
  Sparkles,
  Layers,
} from 'lucide-vue-next'
const props = defineProps<{ name: string; size?: number }>()
const icons = {
  arrow: ArrowRight,
  external: ArrowUpRight,
  search: Search,
  down: ChevronDown,
  right: ChevronRight,
  check: Check,
  copy: Copy,
  menu: Menu,
  close: X,
  sun: Sun,
  moon: Moon,
  github: Github,
  globe: Globe,
  book: BookOpen,
  code: Code2,
  terminal: Terminal,
  box: Box,
  blocks: Blocks,
  compass: Compass,
  file: FileCode2,
  folder: FolderTree,
  braces: Braces,
  rocket: Rocket,
  workflow: Workflow,
  layout: LayoutDashboard,
  database: Database,
  network: Network,
  git: GitBranch,
  clock: Clock3,
  command: Command,
  help: CircleHelp,
  filter: SlidersHorizontal,
  link: ExternalLink,
  list: List,
  complete: CheckCircle2,
  sparkles: Sparkles,
  layers: Layers,
}
const icon = computed(() => icons[props.name as keyof typeof icons] || BookOpen)
</script>
<template>
  <component :is="icon" :size="size || 18" :stroke-width="1.65" aria-hidden="true" />
</template>
